# fly.toml

app = "garbageidentify"
primary_region = "sin"
kill_signal = "SIGTERM"

[build]

[env]
  PHX_HOST = "garbageidentify.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true  # Changed from 'stop' to true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Add health check
  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024